### ISSUE TITLE
Allow bindings to another keys

### ISSUE THREAD

**Issue by kovetskiy** [grafov/shift-shift#4]
Hi!

What you think about allowing bindings to another keys, for example, bind eng to left control and bind rus to right control? If you not against this feature, I can implement this.

Why I want this feature? I swaped my keys with xkb:
CapsLock = Control_L
Shift_L = Escape
Control_L = Shift_L (I press Control_L by wrist, very-very useful with mechanical keyboard)
This map is very useful for my workflow, but now I have a trouble with switching to english language (Xorg server things I pressed the escape button, and VIm in this moment goes to NORMAL mode)

**Comment by grafov** [comment]
Personally I satisfied with current functionality but I will glad to accept new features. Pull requests are welcome if they will not break default settings and logic.
